import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class FoxAndGomoku
{
	public String win(String[] board)
	{
		for (int i = 0; i < board.length; i++) {
			for (int j = 0; j < board[i].length(); j++) {
				char curr = board[i].charAt(j);
				if (curr != 'o') continue;
				
				boolean hori = true, vert = true, diag1 = true, diag2 = true;
				for (int x = 1; x < 5; x++) {
					
					int jx = j+x;
					int ix = i+x;
					int jjx = j-x;
					int iix = i-x;
					
					if ((jx >= board[i].length()) || (hori && board[i].charAt(jx) != 'o')) hori = false;
					if ((ix >= board.length) || (vert && board[ix].charAt(j) != 'o')) vert = false;
					if ((ix >= board.length || jx >= board[ix].length()) || (diag1 && board[ix].charAt(jx) != 'o')) diag1 = false;
					if ((jjx < 0 || iix >= board.length) || (diag2 && board[ix].charAt(jjx) != 'o')) diag2 = false;
				}
				
				if (hori || vert || diag1 || diag2) return "found";
			}
		}
		
		return "not found";
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		FoxAndGomoku obj;
		String answer;
		obj = new FoxAndGomoku();
		long startTime = System.currentTimeMillis();
		answer = obj.win(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String p1;
		
		// ----- test 0 -----
		p0 = new String[]{"....o.","...o..","..o...",".o....","o.....","......"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"oooo.",".oooo","oooo.",".oooo","....."};
		p1 = "not found";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"oooo.",".oooo","oooo.",".oooo","....o"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"o.....",".o....","..o...","...o..","....o.","......"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"o....","o.o..","o.o.o","o.o..","o...."};
		p1 = "found";
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new String[]{"..........","..........","..oooooo..","..o.......","..o.......","..oooooo..",".......o..",".......o..","..oooooo..",".........."};
		p1 = "found";
		all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 6 -----
		p0 = new String[]{"..........","..........","..oooo.o..","..o.......","..o.......","..o.oooo..",".......o..",".......o..","..oooo.o..",".........."};
		p1 = "not found";
		all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 7 -----
		p0 = new String[]{"ooooo","ooooo","ooooo","ooooo","ooooo"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 8 -----
		p0 = new String[]{".....",".....",".....",".....","....."};
		p1 = "not found";
		all_right = KawigiEdit_RunTest(8, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
